### ISSUE TITLE
SimpleTag

### ISSUE THREAD

**Issue by carprez** [shred/commons-taglib#1]
Hi,

I've been trying to create a SimpleTag, but doTag() method is never executed. 

My class is annotated in this way:

```
@Component
@Tag(bodycontent = "empty", type = SimpleTag.class)
@Scope(BeanDefinition.SCOPE_PROTOTYPE)
public class CustomTag extends SimpleTagSupport {
```

After some research, I've modified doTag() method in SimpleTagProxy class:

```
public void doTag() throws JspException, IOException {
    getTargetBean().doTag();
}
```

It works but I'd like to know if this modification breaks anything else.

Thanks

**Comment by shred** [comment]
Thank you for reporting this issue. Actually, it's a bug in commons-taglib. It is supposed to work out of the box.

I will deploy a fixed version shortly...

**Comment by shred** [comment]
Version 2.1 contains your bugfix. It is available here and at Maven Central.
